# Generated by Django 4.1 on 2022-09-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_employer",
            field=models.BooleanField(default=False, help_text="Signup as an employer"),
        ),
    ]
