# Generated by Django 4.1 on 2022-09-01 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_is_employer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_employer",
        ),
    ]
