# Generated by Django 4.1 on 2022-09-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile_signup_confirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="type",
            field=models.CharField(
                choices=[("Candidate", "Candidate"), ("Employer", "Employer")],
                default="Candidate",
                max_length=20,
            ),
        ),
    ]
