# Generated by Django 4.1 on 2022-09-01 16:42

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_profile_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the certificate", max_length=200
                    ),
                ),
                (
                    "about",
                    ckeditor.fields.RichTextField(
                        help_text="Brief info about the certificate"
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        help_text="Where did you get the certificate", max_length=200
                    ),
                ),
                ("year", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="Country",
            field=django_countries.fields.CountryField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="behance",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="bitbucket",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("BEGINNER", "Beginner"),
                    ("INTERMEDIATE", "Intermediate"),
                    ("SENIOR", "Senior"),
                ],
                default="BEGINNER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="facebook",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="github",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gitlab",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="job_title",
            field=models.CharField(
                help_text="Javascript Developer", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="portfolio",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, null=True, populate_from="user", unique=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="certificates",
            field=models.ManyToManyField(to="users.certificate"),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.ManyToManyField(to="users.skill"),
        ),
    ]
