# Generated by Django 4.1 on 2022-09-01 16:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_certificate_skill_profile_country_profile_behance_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="job_title",
            new_name="Profession",
        ),
        migrations.AlterField(
            model_name="profile",
            name="behance",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=ckeditor.fields.RichTextField(
                help_text="Tell employers about yourself", null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bitbucket",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="certificates",
            field=models.ManyToManyField(blank=True, to="users.certificate"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gitlab",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="portfolio",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skills",
            field=models.ManyToManyField(blank=True, to="users.skill"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
    ]
