# Generated by Django 4.1 on 2022-09-01 17:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_rename_job_title_profile_profession_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="Profession",
            field=models.CharField(
                blank=True, help_text="Javascript Developer", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=ckeditor.fields.RichTextField(
                blank=True, help_text="Tell employers about yourself", null=True
            ),
        ),
    ]
