# Generated by Django 4.1 on 2022-09-01 17:03

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_profile_profession_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="Country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=100, null=True
            ),
        ),
    ]
