# Generated by Django 4.1 on 2022-08-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recruiters",
            "0004_remove_job_category_remove_job_skills_job_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="category",
            field=models.ManyToManyField(to="recruiters.category"),
        ),
        migrations.AlterField(
            model_name="job",
            name="skills",
            field=models.ManyToManyField(to="recruiters.skill"),
        ),
    ]
