# Generated by Django 4.1 on 2022-08-25 09:05

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0005_alter_job_category_alter_job_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="ghgj", editable=False, populate_from="name", unique=True
            ),
            preserve_default=False,
        ),
    ]
