# Generated by Django 4.1 on 2022-08-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0006_category_is_active_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
