# Generated by Django 4.1 on 2022-08-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0008_alter_category_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(default="lni lni-laptop-phone", max_length=50),
        ),
    ]
