# Generated by Django 4.1 on 2022-08-25 10:02

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0010_company_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="fggh", editable=False, populate_from="title", unique=True
            ),
            preserve_default=False,
        ),
    ]
