# Generated by Django 4.1 on 2022-08-26 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recruiters", "0013_alter_job_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="recruiter",
        ),
        migrations.AddField(
            model_name="company",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="recruiters.company",
            ),
        ),
    ]
