# Generated by Django 4.1 on 2022-08-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0014_remove_job_recruiter_company_owner_alter_job_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="deadline",
            field=models.DateField(null=True),
        ),
    ]
