# Generated by Django 4.1 on 2022-08-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0018_job_recruiter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="deadline",
        ),
    ]
