# Generated by Django 4.1 on 2022-08-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0019_remove_job_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="job",
            name="category",
        ),
        migrations.RemoveField(
            model_name="job",
            name="company",
        ),
        migrations.RemoveField(
            model_name="job",
            name="experience_level",
        ),
        migrations.RemoveField(
            model_name="job",
            name="recruiter",
        ),
        migrations.RemoveField(
            model_name="job",
            name="skills",
        ),
        migrations.RemoveField(
            model_name="job",
            name="type",
        ),
    ]
