# Generated by Django 4.1 on 2022-08-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "recruiters",
            "0021_job_banner_job_category_job_company_job_deadline_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="job",
            name="category",
        ),
        migrations.RemoveField(
            model_name="job",
            name="company",
        ),
        migrations.RemoveField(
            model_name="job",
            name="skills",
        ),
    ]
