# Generated by Django 4.1 on 2022-08-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0022_remove_job_banner_remove_job_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="deadline",
        ),
        migrations.RemoveField(
            model_name="job",
            name="experience_level",
        ),
        migrations.RemoveField(
            model_name="job",
            name="type",
        ),
    ]
