# Generated by Django 4.1 on 2022-08-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0023_remove_job_deadline_remove_job_experience_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="banner",
            field=models.ImageField(default="fg", upload_to="job_banners"),
            preserve_default=False,
        ),
    ]
