# Generated by Django 4.1 on 2022-08-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0024_job_banner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="banner",
        ),
        migrations.AddField(
            model_name="job",
            name="skills",
            field=models.ManyToManyField(to="recruiters.skill"),
        ),
    ]
