# Generated by Django 4.1 on 2022-08-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0026_job_experience_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="deadline",
            field=models.DateField(null=True),
        ),
    ]
