# Generated by Django 4.1 on 2022-08-26 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0027_job_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.ManyToManyField(to="recruiters.category"),
        ),
        migrations.AddField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="recruiters.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="type",
            field=models.CharField(
                choices=[
                    ("Full Time", "Full Time"),
                    ("Internship", "Internship"),
                    ("Remote", "Remote"),
                ],
                default="Full Time",
                max_length=50,
            ),
        ),
    ]
