# Generated by Django 4.1 on 2022-08-21 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recruiters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=50)),
                ("job_title", models.CharField(max_length=100)),
                ("started", models.DateTimeField()),
                ("ended", models.DateTimeField()),
                ("about", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the qualification.", max_length=200
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        help_text="Institution you got it from.", max_length=100
                    ),
                ),
                ("year", models.DateTimeField()),
                (
                    "about",
                    models.TextField(help_text="Brief info about this qualification."),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Provide your name", max_length=200),
                ),
                (
                    "title",
                    models.CharField(help_text="Eg. Web Developer", max_length=100),
                ),
                (
                    "location",
                    models.CharField(help_text="Eg. Aba, Abia State", max_length=100),
                ),
                (
                    "looking_for",
                    models.CharField(
                        choices=[
                            ("Full Time", "Full Time"),
                            ("Internship", "Internship"),
                            ("Remote", "Remote"),
                        ],
                        default="Remote",
                        max_length=50,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Intermediate", "Intermediate"),
                            ("Senior", "Senior"),
                        ],
                        default="Beginner",
                        max_length=50,
                    ),
                ),
                (
                    "qualifications",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidates.qualification",
                    ),
                ),
                (
                    "skills",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recruiters.skill",
                    ),
                ),
            ],
        ),
    ]
