# Generated by Django 4.1 on 2022-08-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_remove_candidate_skills_candidate_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="photo",
            field=models.ImageField(null=True, upload_to="photos/candidates"),
        ),
    ]
