# Generated by Django 4.1 on 2022-08-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_candidate_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="top",
            field=models.BooleanField(default=False),
        ),
    ]
