# Generated by Django 4.1 on 2022-08-26 12:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0007_profile_is_candidate_profile_is_employer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=ckeditor.fields.RichTextField(default="hj"),
            preserve_default=False,
        ),
    ]
