# Generated by Django 4.1 on 2022-08-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0009_profile_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="qualifications",
        ),
        migrations.AddField(
            model_name="profile",
            name="qualifications",
            field=models.ManyToManyField(to="candidates.qualification"),
        ),
    ]
