# Generated by Django 4.1 on 2022-08-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0010_remove_profile_qualifications_profile_qualifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_candidate",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_employer",
        ),
    ]
